version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    ports:
      - 3000:3000
    networks:
      - internal
    volumes:
      - type: volume
        source: pdf
        target: /app/resources/pdf
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: mongodb
    ports:
      - 27017-27019:27017-27019
    networks:
      - internal
    volumes:
      - type: volume
        source: mongodb_data
        target: /data/db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    ports:
      - 5000:5000
    networks:
      - internal

networks:
  internal:
    driver: bridge
    driver_opts:
       com.docker.network.bridge.name: "brinterna"
       
volumes:
  pdf:
    external: true
  mongodb_data:
    external: true

