version: '3'

services:
  guessr_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: guessr_server
    ports:
      - 3000:3000
    networks:
      - internal
    volumes:
      - ./resources:/resources
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: mongodb
    ports:
      - 27017-27019:27017-27019
    networks:
      - internal
    volumes:
      - ./data:/data

networks:
  internal:
    driver: bridge
    driver_opts:
       com.docker.network.bridge.name: "brinterna"

